apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eudiplo-ingress
  annotations:
    # Add your ingress controller annotations here
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: eudiplo.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eudiplo
                port:
                  number: 3000
    - host: eudiplo-client.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eudiplo-client
                port:
                  number: 80
